### ISSUE TITLE
unmet dependencies "libgl1-mesa-glx"

### ISSUE THREAD

**Issue by freewee** [gkv311/sview#131]
Hi Kirill

When trying to install sView in Ubuntu 24.04,with repository, I have this error:

The following packages have unmet dependencies:
sview : Depends: libgl1-mesa-glx (>= 7.7) but it is not installable
E: Unable to fix problems, broken packages are in "keep as is" mode

Is it possible to correct it?
Thank you

**Comment by gkv311** [comment]
Could you point out how you have fixed it (maybe something could be improved in sView scripts)?

**Comment by freewee** [comment]
Hi
The libgl1-mesa-glx is available as .deb (https://pkgs.org/download/libgl1-mesa-glx) but is intended to Ubuntu 22.04. This package installs however in Mint 22 (24.04) where it was missing ... So after that no problem for sView!
I am more often under Linux Mint, but I am in multi boot, I was curious to see how sView could install in Ubuntu 24.04.1: no problem because the libgl1-mesa-glx is present (as transitional dummy package), but I don't know if it is natively present...
Thank you

**Comment by ddska** [comment]
@gkv311 
`libgl1-mesa-glx` has been a transitional package for a while and is now obsolete from Ubuntu 23.10 and onwards.

Dependency should be replaced with  `libgl1` and `libglx-mesa0`.

**Comment by gkv311** [comment]
This should be fixed by e3e85b37515e36ae90b485b05f1fbce6f77d6567, but packages in PPA haven't been updated (yet).

**Comment by ddska** [comment]
Still can't install on Ubuntu 24.04.
@gkv311 any plans to update PPA packages?
